### ISSUE TITLE
Update to include fixes for system tray icons

### ISSUE THREAD

**Issue by taprobane99** [doncsugar/Genome-Spectrum#2]
On the latest Breeze themes (5.21.5 but perhaps earlier) the system tray icons have better spacing, especially on high dpi displays. More specifically the top and bottom margins of the system tray area has been increased. On "scale with panel height" they don't end up almost touching the borders of the panel at larger panel heights.

 Can the Spectrum themes be updated to include those changes?

**Comment by doncsugar** [comment]
I am not entirely sure if it can be updated. The new update helped by allowing Task Manager assets to scale to the full height of the panel, but the theme relies on the hint "no-border-padding" and removing it means that the normally full-height indicator for the start menu and system tray will have margins. I can add an alternative plasma theme if you are fine with that.

**Comment by taprobane99** [comment]
ok, yes that would work. I also noticed that the left-right spacing of system tray icons is much improved in recent breeze. before they were too widely spaced (at least on my system). so, definitely an alternative theme would be very useful for me to continue using Spectrum.

**Comment by doncsugar** [comment]
I added a "hidpi" version to the [neutral theme](https://www.pling.com/p/1449495/). If this works properly, I will add a variant for Dark and Light.

**Comment by taprobane99** [comment]
yes, works perfectly! system tray icons all in exactly same positions as latest breeze

**Comment by doncsugar** [comment]
I have added variants for [Dark and Light](https://github.com/doncsugar/Genome-Spectrum/commit/4cd2dac339f586b16927c1e0c1bc68fd0429a16c).
