### ISSUE TITLE
User color shemes

### ISSUE THREAD

**Issue by Nikita-Presnov** [doncsugar/Genome-Spectrum#3]
I really liked your "Genome Light and Dark Kvantum" design, but some things, for example, the background of buttons and menus and as far as I understand the fonts are nailed, what to do in a good way is wrong.

![изображение](https://user-images.githubusercontent.com/54064458/121971138-bb7d6f80-cd80-11eb-9c0c-3f08d138f5ef.png)

Now for more details.
I like the blur and the default breeze dark theme, but because the default color scheme is unmistakably bluish, my eyes start to hurt. I solved it just by editing the color scheme itself, but when I uploaded your artwork, it prevents it from being applied to the end, which doesn't look very nice.

**Comment by doncsugar** [comment]
Nik, I cannot understand what you are saying. Please post again in Russian. Я не могу понять, о чем вы говорите. Пожалуйста, напишите еще раз на русском языке.

If I am correctly understanding what you are saying, try this:
Download "GenomeSpectrum.zip" from here: https://store.kde.org/p/1510247/

Если я правильно понимаю то, что вы говорите, попробуйте следующее:
Скачайте "GenomeSpectrum.zip" отсюда: https://store.kde.org/p/1510247/.

**Comment by Nikita-Presnov** [comment]
Никак не получается применить свою более "тёплую" цветовую схему к вашей теме квантум, фон кнопок и некоторые другие элементы интерфейса так и остаются тёмно-синими.

**Comment by doncsugar** [comment]
I see. Were you able to solve your problem with this? Я понимаю. Смогли ли вы решить свою проблему с помощью "Spectrum"?

https://store.kde.org/p/1510247/  ->  "GenomeSpectrum.zip"

Kvantum does not allow inheriting those colors. The "changeColors.sh" was made to inherit colors from a ".colors" file. Run the script with your color scheme before installing the theme through Kvantum.
