### ISSUE TITLE
Toolbar transparency

### ISSUE THREAD

**Issue by Sadi58** [doncsugar/Genome-Spectrum#5]
I very much liked the transparency effect in the titlebar and side panels, e.g. in Dolphin.
But when I saw the Kate's Save File dialog box, I thought it would look even better if the toolbar also had that transparency effect (maybe same, maybe just a little different as in Kate's Save File dialog box).
(I use the Kvantum GenomeLight theme with Genome Light color-scheme)
![image](https://user-images.githubusercontent.com/6375934/136816899-0584447e-be5d-42b8-8e9b-1b1b6014f1ae.png)
![image](https://user-images.githubusercontent.com/6375934/136816927-a3bd3a86-35ec-430a-915a-bc18bcfdcd7e.png)

**Comment by doncsugar** [comment]
You can go to GenomeLight.kvconfig and look for [Toolbar]. Under it, change the "toolbar" for interior.element= and frame.element= to something else (I like "toolbarNO") and it will remove the toolbar. Do NOT change the indicator.element line.The same can also be done for the menubar, if you use it.

With Inkscape, you can also change the translucency or colors of the toolbar in the .svg file.

**Comment by Sadi58** [comment]
Thank you!
